<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INBGQT-LT-0460" name="com.poc.twitter.test.GET_statuses_home_timeline_Test" tests="7" failures="2" timestamp="22 Jan 2019 15:05:49 GMT" time="0.072" errors="0">
  <testcase name="T01_SearchSource" time="0.015" classname="com.poc.twitter.test.GET_statuses_home_timeline_Test"/>
  <testcase name="T03_Search_Name" time="0.008" classname="com.poc.twitter.test.GET_statuses_home_timeline_Test"/>
  <testcase name="T04_Search_followers_count" time="0.011" classname="com.poc.twitter.test.GET_statuses_home_timeline_Test"/>
  <testcase name="T06_Search_Statuses_count" time="0.010" classname="com.poc.twitter.test.GET_statuses_home_timeline_Test">
    <failure type="java.lang.AssertionError" message="Status count is wrong! expected:&lt;181&gt; but was:&lt;190&gt;">
      <![CDATA[java.lang.AssertionError: Status count is wrong! expected:<181> but was:<190>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at com.poc.twitter.test.GET_statuses_home_timeline_Test.T06_Search_Statuses_count(GET_statuses_home_timeline_Test.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- T06_Search_Statuses_count -->
  <testcase name="T02_Search_Screen_name" time="0.008" classname="com.poc.twitter.test.GET_statuses_home_timeline_Test"/>
  <testcase name="T07_Search_Statuses_text" time="0.010" classname="com.poc.twitter.test.GET_statuses_home_timeline_Test">
    <failure type="org.junit.ComparisonFailure" message="Status text is wrong! expected:&lt;...ing this tweet with [Mon Jan 21 17:44:43] IST 2019 Automation&gt; but was:&lt;...ing this tweet with [Tue Jan 22 20:34:22] IST 2019 Automation&gt;">
      <![CDATA[org.junit.ComparisonFailure: Status text is wrong! expected:<...ing this tweet with [Mon Jan 21 17:44:43] IST 2019 Automation> but was:<...ing this tweet with [Tue Jan 22 20:34:22] IST 2019 Automation>
at org.junit.Assert.assertEquals(Assert.java:115)
at com.poc.twitter.test.GET_statuses_home_timeline_Test.T07_Search_Statuses_text(GET_statuses_home_timeline_Test.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- T07_Search_Statuses_text -->
  <testcase name="T05_Search_friends_count" time="0.010" classname="com.poc.twitter.test.GET_statuses_home_timeline_Test"/>
</testsuite> <!-- com.poc.twitter.test.GET_statuses_home_timeline_Test -->
