<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="INBGQT-LT-0460" name="com.poc.twitter.test.POST_statuses_update" tests="6" failures="1" timestamp="03 Jan 2019 11:44:27 GMT" time="0.492" errors="0">
  <testcase name="T02_Search_Screen_name" time="0.007" classname="com.poc.twitter.test.POST_statuses_update"/>
  <testcase name="T03_Search_Name" time="0.005" classname="com.poc.twitter.test.POST_statuses_update"/>
  <testcase name="T06_Search_Statuses_count" time="0.007" classname="com.poc.twitter.test.POST_statuses_update">
    <failure type="java.lang.AssertionError" message="Status count is wrong! expected:&lt;165&gt; but was:&lt;166&gt;">
      <![CDATA[java.lang.AssertionError: Status count is wrong! expected:<165> but was:<166>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at com.poc.twitter.test.POST_statuses_update.T06_Search_Statuses_count(POST_statuses_update.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- T06_Search_Statuses_count -->
  <testcase name="T05_Search_friends_count" time="0.005" classname="com.poc.twitter.test.POST_statuses_update"/>
  <testcase name="T04_Search_followers_count" time="0.005" classname="com.poc.twitter.test.POST_statuses_update"/>
  <testcase name="T01_SearchSource" time="0.463" classname="com.poc.twitter.test.POST_statuses_update"/>
</testsuite> <!-- com.poc.twitter.test.POST_statuses_update -->
